# Phoenix Life Configuration

# Default round timer duration in seconds (10800 = 3 hours)
round-duration: 10800

# Whether the game starts paused
start-paused: true

# Messages configuration
messages:
  death-with-lives: "&cYou died! You have %lives% lives remaining."
  elimination: "&c%player% has been eliminated!"
  game-start: "&aThe Phoenix Life game has started!"
  game-pause: "&eThe game has been paused. Deaths will not deduct lives."
  game-resume: "&aThe game has been resumed. Deaths will deduct lives again."